version: "3.9"
services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "29092:29092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://127.0.0.1:29092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      interval: 2s
      timeout: 5s
      retries: 10
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "kafka:9092"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
  kafka-define-topic:
    depends_on:
      kafka:
        condition: service_healthy
    build: .
    command: ["bundle", "exec", "ruby", "kafka/admin.rb"]
  kafka-watcher:
    depends_on:
      kafka-define-topic:
        condition: service_completed_successfully
    build: .
    command: ["bundle", "exec", "ruby", "kafka/watcher.rb"]
  kafka-consumer:
    depends_on:
      kafka-define-topic:
        condition: service_completed_successfully
    build: .
    command: ["bundle", "exec", "ruby", "kafka/consumer.rb"]
    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
  beanstalkd:
    build:
      dockerfile: Dockerfile.beanstalkd
    ports:
      - "11300:11300"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
  beanstalkd-watcher:
    depends_on:
      - beanstalkd
    build: .
    command: ["bundle", "exec", "ruby", "beanstalkd/watcher.rb"]
  beanstalkd-consumer:
    depends_on:
      - beanstalkd
    build: .
    command: ["bundle", "exec", "ruby", "beanstalkd/consumer.rb"]
    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          cpus: "0.2"
          memory: 256M